### ISSUE TITLE
Is this package abandoned, or just finished?

### ISSUE THREAD

**Issue by naugtur** [tracker1/node-rsa-pem-from-mod-exp#2]
I'm just checking if you (author) are still here. 
This does exactly what I need, but I'm not sure if I can assume it's production-usable.

**Comment by tracker1** [comment]
It's done... there might be the opportunity for some code cleanup, but as it is, it works... there are several projects using this for jwt/auth methods, which is what I created it for... it is used in some relatively popular systems online.

One thing that may be desired to adjust would be the use of Buffer, which means that a Buffer polyfill will be needed if used client-side (which Browserify/Webpack should include).

**Comment by naugtur** [comment]
Great, thanks for quick response!

Open-source is awesome.
