### ISSUE TITLE
Missing prefix when generating PEM

### ISSUE THREAD

**Issue by McPo** [tracker1/node-rsa-pem-from-mod-exp#3]
My use case is to obtain the SPKI of a SSL Certificate. However I have noticed when generating the PEM file of the public key (From the correct exponent and and modulus). There appears to be a prefix missing. I have attempted this with several certificate including the GitHub cert for example.

Download the cert from GitHub (I used Safari, and dragged and dropped it)
Covert the cert to PEM `openssl x509 -inform der -in *.github.com.cer -out *.github.com.pem`
Extract the public key using OpenSSL to PEM `openssl x509 -pubkey -noout -in \*.github.com.pem`

Now use the following script (Im aware other 3rd party libraries are being used, however the exponent and modulus are correctly extracted, the issue comes from forming the PEM)
```
const fs = require('fs');
const x509 = require('x509.js');
const getPem = require('rsa-pem-from-mod-exp');
const crypto = require('crypto');

const cert = fs.readFileSync('./*.github.com.pem');

const parsedData = x509.parseCert(cert);
const publicModulusB64 = Buffer.from(parsedData['publicModulus'], 'hex').toString('base64');
const publicExponentB64 = Buffer.from(parsedData['publicExponent'], 'hex').toString('base64');

const prefix = '';//'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A';

const publicKeyPem = getPem(publicModulusB64, publicExponentB64);
const publicKeyB64 = publicKeyPem.split('\n').slice(1, -2).join('');
const spki = crypto.createHash('sha256').update(prefix+publicKeyB64, 'base64').digest('base64');

console.log(publicKeyPem);
console.log(spki);
```

You will notice the public key generated by the script is missing the prefix
> MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A

It seems OpenSSL is spending some information to the public key, and this may not be possible with this library as it only has exponent and modulus to work with. Figured Id highlight it at least. Are you aware of why there would be a discrepancy?

**Comment by McPo** [comment]
So apparently the issue is due to you generating an RSA Public Key as opposed to a Public Key (PKCS#1 vs PKCS#8).

Some useful links:
- https://severehalestorm.net/?cat=5
- http://www.sivachandran.in/2012/09/exporting-rsa-public-key-in-pkcs1-format.html
- https://stackoverflow.com/a/12713287/1167880

As the library is called "node-rsa-pem-from-mod-exp", it's defensibly not an issue, but still prefer to highlight it, incase any other users run into issues.

**Comment by ademakanaky** [comment]
> So apparently the issue is due to you generating an RSA Public Key as opposed to a Public Key (PKCS#1 vs PKCS#8).
> 
> Some useful links:
> 
> * https://severehalestorm.net/?cat=5
> * http://www.sivachandran.in/2012/09/exporting-rsa-public-key-in-pkcs1-format.html
> * https://stackoverflow.com/a/12713287/1167880
> 
> As the library is called "node-rsa-pem-from-mod-exp", it's defensibly not an issue, but still prefer to highlight it, incase any other users run into issues.

Thanks for your info. I currently have issues with generating a working public key using the modulus and exponent. I keep getting the following error:

$ openssl rsautl -in file.txt -encrypt -pubin -inkey public.pub >datafile.enc
RSA operation error
7768:error:04068065:rsa routines:RSA_EAY_PUBLIC_ENCRYPT:bad e value:rsa_eay.c:169:
Kindly assist me with this.

**Comment by tracker1** [comment]
I'll have to look into it... I haven't actually touched this in years, it was created really early on for JWT support, and worked for the case I was using it with.  Will see about updating it.  :-)
